name: Bug Report
description: Report a visual glitch, missing highlight group, or issue with a port
title: "[Bug]: "
labels: ["bug"]
body:
  - type: input
    id: port_name
    attributes:
      label: Which port is this regarding?
      description: e.g. Neovim, VS Code, Ghostty
      placeholder: VS Code
    validations:
      required: true
  - type: textarea
    id: bug_description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
